server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 30
    connection-timeout: 5000ms
  port: 8080
  servlet:
    context-path: /emoss-wxx-api





spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:
      username: root
      password: 
      initial-size: 8
      max-active: 16
      min-idle: 8
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

  redis:
    database: 0
    host: localhost
    port: 
    password: 
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8

  data:
    mongodb:
      host: localhost
      port: 
      database: emoss
      authentication-database: 
      username: 
      password:
  mail:
    default-encoding: UTF-8
    host: smtp.aliyun.com
    username:
    password:
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.emos.wx.db.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.example.emos.wx.db.dao : warn
  pattern:
    console: "%d{HH:mm:ss}  %-5level  %msg%n"
emos:
  jwt:
    secret:
    expire: 5
    cache-expire: 10
  face:
    createFaceModelUrl: http:/
    checkinUrl: http
  email:
    system: Fe
    hr: 23
  image-folder: E:\emoss\emoss-wxx-api\image
  code: youdonothavecode
wx:
  app-id: wx
  app-secret: d
